### ISSUE TITLE
Calendar

### ISSUE THREAD

**Issue by sfactor** [antonshirokov/nsudotnet#1]
Подозрительно похоже на https://github.com/chuldiana/nsudotnet/blob/master/Chul.Nsudotnet.Calendar/Chul.Nsudotnet.Calendar/Program.cs. Не зачитываю

**Comment by antonshirokov** [comment]
Да, чем-то они похоже.Каждый сам писал свою лабу.
Программа настолько маленькая, что все календари похожи в чем-то.
Могу переписать лабу со всякими извращениями, чтобы Вы не сомневались, что лабу писал я.

**Comment by sfactor** [comment]
До этого у вас код был одинаков с точностью до порядка операций и имен переменных.

Сейчас зачитываю, 1 балл
